In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits=load_digits()

In [2]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,random_state=101,test_size=0.2)


In [4]:
lr=LinearRegression()

In [5]:
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.5474092214842982

In [6]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9944444444444445

In [7]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9805555555555555

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def getscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [26]:
from sklearn.model_selection import StratifiedKFold

In [29]:
score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_l.append(getscore(LinearRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(getscore(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(getscore(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [30]:
score_l

[0.5210503111571496, 0.5681424219493627, 0.41943985059688305]

In [32]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
score_rf

[0.9365609348914858, 0.9532554257095158, 0.9315525876460768]

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LinearRegression(),digits.data,digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [36]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.90277778, 0.95821727, 0.96657382, 0.9275766 ])