In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [66]:
df=pd.read_csv('TATAMOTORS.NS.csv',index_col=[0])
df.head()

Open        High         Low       Close   Adj Close    Volume
Date                                                                       
2022-08-23  449.0  462.100006  447.600006  460.450012  459.019379  17779238
2022-08-24  459.0  464.899994  457.700012  463.200012  461.760834  12214113
2022-08-25  466.0  468.799988  457.399994  459.200012  457.773285  11255809
2022-08-26  465.0  470.450012  463.950012  465.049988  463.605072  11252560
2022-08-29  451.0  456.899994  450.149994  453.350006  451.941437  11647725

In [22]:
df1=df[['Close']]
df1=df1.rename(columns={'Close':'Actual_Close'})
df1.head()
df1['Target']=df1.rolling(2).apply(lambda x:x.iloc[1]>x.iloc[0])
df1

Actual_Close  Target
Date                            
2022-08-23    460.450012     NaN
2022-08-24    463.200012     1.0
2022-08-25    459.200012     0.0
2022-08-26    465.049988     1.0
2022-08-29    453.350006     0.0
...                  ...     ...
2023-08-16    618.750000     1.0
2023-08-17    613.750000     0.0
2023-08-18    615.799988     1.0
2023-08-21    620.500000     1.0
2023-08-22    620.200012     0.0

[248 rows x 2 columns]

In [23]:
df2=df.copy()
df2=df2.shift(1)
print(df2)
print(df1)

                  Open        High         Low       Close   Adj Close  \
Date                                                                     
2022-08-23         NaN         NaN         NaN         NaN         NaN   
2022-08-24  449.000000  462.100006  447.600006  460.450012  459.019379   
2022-08-25  459.000000  464.899994  457.700012  463.200012  461.760834   
2022-08-26  466.000000  468.799988  457.399994  459.200012  457.773285   
2022-08-29  465.000000  470.450012  463.950012  465.049988  463.605072   
...                ...         ...         ...         ...         ...   
2023-08-16  612.000000  612.000000  594.500000  607.349976  607.349976   
2023-08-17  606.700012  621.349976  597.299988  618.750000  618.750000   
2023-08-18  620.000000  622.000000  611.000000  613.750000  613.750000   
2023-08-21  612.799988  620.099976  610.900024  615.799988  615.799988   
2023-08-22  617.000000  623.299988  614.799988  620.500000  620.500000   

                Volume  
Date        

In [32]:
predictors=['Close','Volume','Open','High','Low']
df1=df1.join(df2[predictors])
df1.head()


ValueError: columns overlap but no suffix specified: Index(['Close', 'Volume', 'Open', 'High', 'Low'], dtype='object')

In [40]:
final_df=df1.iloc[1:]
final_df

Actual_Close  Target       Close      Volume        Open  \
Date                                                                   
2022-08-24    463.200012     1.0  460.450012  17779238.0  449.000000   
2022-08-25    459.200012     0.0  463.200012  12214113.0  459.000000   
2022-08-26    465.049988     1.0  459.200012  11255809.0  466.000000   
2022-08-29    453.350006     0.0  465.049988  11252560.0  465.000000   
2022-08-30    471.100006     1.0  453.350006  11647725.0  451.000000   
...                  ...     ...         ...         ...         ...   
2023-08-16    618.750000     1.0  607.349976  14492164.0  612.000000   
2023-08-17    613.750000     0.0  618.750000  14562074.0  606.700012   
2023-08-18    615.799988     1.0  613.750000  12119293.0  620.000000   
2023-08-21    620.500000     1.0  615.799988  11190760.0  612.799988   
2023-08-22    620.200012     0.0  620.500000   9580365.0  617.000000   

                  High         Low  
Date                                
2022-08-24  462.100006  447.600006  
2022-08-25  464.899994  457.700012  
2022-08-26  468.799988  457.399994  
2022-08-29  470.450012  463.950012  
2022-08-30  456.899994  450.149994  
...                ...         ...  
2023-08-16  612.000000  594.500000  
2023-08-17  621.349976  597.299988  
2023-08-18  622.000000  611.000000  
2023-08-21  620.099976  610.900024  
2023-08-22  623.299988  614.799988  

[247 rows x 7 columns]

In [41]:
x=final_df.drop('Target',axis=1)
y=final_df['Target']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=101)

In [60]:
x_test

Actual_Close       Close      Volume        Open        High  \
Date                                                                       
2022-11-15    437.149994  433.700012  17996083.0  424.000000  437.700012   
2022-12-20    410.500000  418.000000   9809103.0  421.899994  422.850006   
2023-03-27    412.049988  416.500000   6877960.0  419.000000  420.549988   
2023-02-14    440.549988  441.049988   8333767.0  445.500000  446.899994   
2022-12-30    387.950012  385.899994  15627403.0  389.000000  390.000000   
...                  ...         ...         ...         ...         ...   
2022-12-19    418.000000  421.600006  50949198.0  417.350006  427.799988   
2022-08-25    459.200012  463.200012  12214113.0  459.000000  464.899994   
2022-10-27    407.700012  404.549988  17979661.0  404.350006  410.500000   
2022-12-01    438.250000  439.399994  14727892.0  435.000000  441.000000   
2023-04-12    465.500000  458.700012  14495222.0  463.750000  463.750000   

                   Low  
Date                    
2022-11-15  423.500000  
2022-12-20  415.500000  
2023-03-27  414.799988  
2023-02-14  438.899994  
2022-12-30  383.049988  
...                ...  
2022-12-19  413.100006  
2022-08-25  457.700012  
2022-10-27  403.200012  
2022-12-01  433.299988  
2023-04-12  455.799988  

[99 rows x 6 columns]

In [64]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)
predictions=logmodel.predict(x_test)
predictions

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.array(y_test)

array([1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.])

In [46]:
from sklearn.metrics import classification_report , confusion_matrix

In [58]:
classification_report(y_test,predictions)

'              precision    recall  f1-score   support\n\n         0.0       0.47      1.00      0.64        46\n         1.0       1.00      0.02      0.04        53\n\n    accuracy                           0.47        99\n   macro avg       0.73      0.51      0.34        99\nweighted avg       0.75      0.47      0.32        99\n'

In [59]:
confusion_matrix(y_test,predictions)

array([[46,  0],
       [52,  1]], dtype=int64)